In [11]:
import numpy as np
np.random.seed(0) # начальное значение для целей воспроизводимости
x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

In [1]:
from sklearn.linear_model import Ridge
import numpy as np

alpha=1.0

X = np.array( [ [0,3], [1,2], [2,1], [3,0] ] )
y = np.array( [ 0, 1, 0, 3 ] )

#expand X by 1.0 column

X = np.insert(X, 0, values=1, axis=1 )

model = Ridge(alpha=alpha, fit_intercept=False )
model.fit(X, y )

print("coef:", model.coef_)

coef: [ 0.17391304  0.62450593 -0.1027668 ]


In [28]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [21]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32


In [25]:
print(x2[0,3])

4


In [32]:
np.arange(5,44)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43])

In [14]:
lst = [1, 2, 3, 4, 5]
np.array(lst)


array([1, 2, 3, 4, 5])

In [18]:
np.random.random((3,3))

array([[0.44171092, 0.97958673, 0.35944446],
       [0.48089353, 0.68866118, 0.88047589],
       [0.91823547, 0.21682214, 0.56518887]])

In [21]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output



In [ ]:
big_array = np.random.randint(1, 100, size=1000000)
%%timeit compute_reciprocals(big_array)

In [27]:
values = np.random.randint(1, 10, size=5)
print(compute_reciprocals(values))
print(1.0 / values)

[0.11111111 0.11111111 0.16666667 1.         0.5       ]
[0.11111111 0.11111111 0.16666667 1.         0.5       ]


In [30]:
x = np.arange(9).reshape((3, 3))
2 * x

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])